return {
    'Disintegration',
    'Invisibility',
    'Tech malfunction',
    'Mutation',
    'Luck drain',
    'Aging acceleration',
    'Time distortion',
    'Necrosis',
    'Light dimming',
    'Poisoning',
    'Plant decay',
    'Stone skin',
    'Elemental imbalance',
    'Frostbite',
    'Silence',
    'Ethereal detachment',
    'Insects swarming',
    'Blood thirst',
    'Animal aggression',
    'Fire touch',
    'Plant growth',
    'Enveloping shadows',
    'Mist thickening',
    'Uncontrollable rage',
    'Petrification',
    'Stars fading',
    'Weather anomalies',
    'Metal rusting',
    'Gravity distortion',
    'Insatiable hunger',
    'Ground trembling',
    'Memory loss',
    'Chronic fatigue',
    'Hallucinations',
    'Magic depletion',
    'Sound distortion',
}
