return {
    'Sleek, aerodynamic profile',
    'Stark, contrasting lines',
    'Liquid, flowing lines',
    'Mirror-polished shine',
    'Opulent gold leaf accents',
    'Delicate, lace-like edges',
    'Floating elements',
    'Enigmatic symbols etched',
    'Embedded precious stones',
    'Fractal-inspired motifs',
    'Minimalist design',
    'Muted, earthy tones',
    'Frosted appearance',
    'Intrincate floral patterns',
    'Elegant filigree details',
    'Rustic, handcrafted look',
    'Natural wood grain',
    'Dark colors and texture',
    'Prismatic reflections',
    'Greaming metallic finish',
    'Rough, stone-like surface',
    'Luminous glow',
    'Flickering effect',
    'Vibrant, shifting hues',
    'Weathered appearance',
    'Imposing structure',
    'Mystic, swirling patterns',
    'Ethereal transparency',
    'Non-reflective texture',
    'Soft, velvety covering',
    'Interlocking assembly',
    'Fluid, organic shapes',
    'Geometric precision',
    'Bioluminescent organisms',
    'Ancient runes inscribed',
    'Rich, deep patina',
}
