return {
    "Assassin's guild",
    "Prophet",
    "City watch commander",
    "Witch coven",
    "High clergy",
    "Divine entity",
    "Scholarly order",
    "Pirate captain",
    "Rebel commander",
    "Technocratic assembly",
    "Oracle",
    "Trade consortium",
    "Warrior chieftain",
    "Local magistrate",
    "Royal family",
    "Ancient being",
    "Elected official",
    "Social reformer",
    "Street gang leader",
    "Noble court",
    "Beast pack alpha",
    "Industry leader",
    "Arcane academy",
    "Elemental warden",
    "Military general",
    "Guildmaster",
    "Artisan's collective",
    "Soverign judge",
    "Merchant guild",
    "Monastic order",
    "Council of elders",
    "Thieves' syndicate",
    "Labor union",
    "Forest guardian",
    "Monarch heir",
    "Necromancer",
}
