return {
    "Tyranny's shadow",
    "Skeleton in every closet",
    "Command under scrutiny",
    "Bloodlines at war",
    "Land under darkness",
    "Marauders attacks",
    "Ancient curse awakens",
    "Supremacy struggle",
    "Vital passage blocked",
    "Rebellion stirs",
    "Dwindling supplies",
    "Mission under threat",
    "Tragic defense failure",
    "Community pillar falls",
    "Treacherous pact",
    "Fickle alliances sour",
    "Energy core unstable",
    "Ancestral land at risk",
    "Poisonous extraction",
    "Epidemic outbreak",
    "Enemies approaching",
    "Disappearances",
    "Heirloom vanishes",
    "Clan feud escalates",
    "Broken promises",
    "Corrupt knowledge",
    "Outsider sparks conflict",
    "Celebration at risk",
    "Invisible killers",
    "Continuous enigma",
    "Caught amidst strife",
    "Plage's spread",
    "Predator's hung",
    "Hazardous ritual",
    "Exile seeks revenge",
    "Ancient rights challenged",
}
