return {
    {
        "Coronation",
        "Artifacts",
        "Arena",
        "Founding",
        "Treaty",
        "Migration",
        "Summit",
        "Discovery",
        "Magic",
        "Prison",
        "Great fire",
        "Piracy",
        "Colony",
        "Sacred grove",
        "Enlightenment",
        "Lost city",
        "Capital",
        "Witch trials",
        "Siege",
        "Battlefield",
        "Monastery",
        "Renaissance",
        "Rebellion",
        "Palace",
        "Pilgrimage",
        "Plague",
        "Revolution",
        "Mine",
        "Gold rush",
        "Industry",
        "Exodus",
        "Sanctuary",
        "Drought",
        "Cataclysm",
        "Inquisition",
        "Burial site",
    },

    {
        "Vineyard",
        "Academy",
        "Art",
        "Market",
        "Trading post",
        "Guildhall",
        "Observatory",
        "Medicine",
        "Sanctuary",
        "Entertainment",
        "Nature",
        "Military",
        "Courthouse",
        "Harbor",
        "Gemstones",
        "Crossroads",
        "Subsistence",
        "Spices",
        "Spirituality",
        "Library",
        "Wisdom",
        "Quarry",
        "Farm",
        "Black market",
        "Festival",
        "Martial arts",
        "Workshop",
        "Garrison",
        "Embassy",
        "Crime",
        "Arcane secrets",
        "Occult",
        "Refuge",
        "Cuisine",
        "Hospitality",
        "Crafting",
    },
}
