return {
    "Moral conflict",
    "Transport issues",
    "Relatives in danger",
    "Ethical dilemma",
    "Strong surveillance",
    "Oath or vow",
    "Language barrier",
    "Espionage or sabotage",
    "Forced secrecy",
    "Hidden agendas",
    "Prophecy or destiny",
    "Unstable environment",
    "Shifting allegiances",
    "Forbidden knowledge",
    "Unknown technology",
    "Political intrigue",
    "Curse or spell",
    "Necessary sacrifice",
    "Resource monopoly",
    "Time-sensitive",
    "Fierce competition",
    "Limited information",
    "Third party interested",
    "Competing interests",
    "Requires specific tool",
    "Difficult terrain",
    "Identity concealment",
    "Scarce resources",
    "Magic protection",
    "Restricted access",
    "Innocents in danger",
    "Cultural taboo",
    "Corrupt authority",
    "Weather hazards",
    "Legal restrictions",
    "Rival claim",
}
