return {
    "Altered past event",
    "Hidden society's rise",
    "Forbidden love revealed",
    "Event was simulation",
    "Game-changing sacrifice",
    "Secret identity",
    "Prophecy's true meaning",
    "Enemy's strong return",
    "Foe's resurrection",
    "Ally's dark history",
    "Greater threat unveiled",
    "Forced nemesis alliance",
    "Manipulated conflict",
    "Double agent revealed",
    "Belief challenged",
    "Love transcends rivalry",
    "Unexpected inheritance",
    "Dead character lives",
    "Villain's true identity",
    "Trusted ally's betrayal",
    "Justified villain actions",
    "Antagonist familial tie",
    "Hidden enemy unveiled",
    "True motive revelation",
    "Antagonist redeemed",
    "Powerful ally",
    "Secret alliance exposed",
    "Shift in allegiance",
    "Past defeat is key",
    "Artifact's sentience",
    "Key character falls",
    "Decoy goal",
    "True lineage revealed",
    "Memory's deception",
    "False victory revealed",
    "Lost power returns",
}
