return {
    "Natural disaster",
    "Covert manipulation",
    "Resources are scarse",
    "Time is running out",
    "Old debt due",
    "Prophecy about you",
    "Powerful obstruction",
    "Moral dilemma",
    "Trust is impossible",
    "Sacrificial decision",
    "Weaknesses exploited",
    "Sinister intentions",
    "Unforeseen consequences",
    "Lost relative found",
    "Erratic transformation",
    "Enemy returns",
    "Uneasy alliance",
    "Key abilities useless",
    "Incomplete information",
    "Decipher message",
    "Events connected",
    "Quest's true nature",
    "Dubious aid needed",
    "Mysterious phenomenon",
    "Paths intertwined",
    "Disguise broken or needed",
    "Past whispers",
    "Power surge",
    "Dark secrets unveiled",
    "Trap or ambush",
    "False crucial intel",
    "Rival factions close in",
    "Conflicting objectives",
    "Necessary reversal",
    "Civilians interfere",
    "Authority overstepped",
}
