return {
    "Guardian beast",
    "Magical artifact",
    "Revealed weakness",
    "Intercepted message",
    "Benefactor's funding",
    "Infiltrated agent",
    "Master craftsman",
    "Local guide",
    "Supernatural ally",
    "Secret code",
    "Expert navigator",
    "Powerful weapon",
    "Network of spies",
    "Cryptic key",
    "Forgotten lore",
    "Essential documents",
    "Hidden vault",
    "Underground network",
    "Legendary spell",
    "Elite mercenary",
    "Allies in high places",
    "Secret passage",
    "Strategic outpost",
    "Special training",
    "Ancient prophecy",
    "Detailed map",
    "Insider information",
    "Wise sage",
    "Advanced technology",
    "Save haven",
    "Protective gear",
    "Ghostly guide",
    "Forgotten hero",
    "Nature spirit",
    "Rebel leader",
    "Divine blessing",
}
