return {
    "You are forced to reconsider your path",
    "A resource thought lost is recovered",
    "A distant event foreshadows an upcoming challenge",
    "An old wound resurfaces at the worst time",
    "An event offers a brief respite",
    "Closure brings about a bittersweet revelation",
    "News of an advancing threat alters priorities",
    "Ambiguity arises from a cryptic message",
    "Fortune shifts with a change of heart",
    "A sudden change in the environment hinders progress",
    "A current context brings about a surprising alliance",
    "A significant step toward a key objective",
    "A mysterious past event becomes crucially clear",
    "A significant clue is discovered",
    "Someone takes a surprising and impactful action",
    "A local dispute draws you into its fold",
    "A message from afar alters your plans",
    "Someone's failure or refusal complicates your plans",
    "Someone's past actions come back to aid you",
    "An unforeseen ally offers assistance",
    "A choice between pursuing or abandoning a goal",
    "An elusive secret is hinted at",
    "A found object leads to new theories",
    "A new threat puts an ally in danger",
    "A trap is sprung",
    "Someone's action forces yo into defense",
    "A positive twist opens a door previously closed",
    "Your talents gain unexpected recognition",
    "A personal challenge that test your resolve",
    "Your progress is thwarted by an unforeseen obstacle",
    "A remote event ties back to a character's past",
    "Someone's success or cooperation opens new paths",
    "A distant ally's plight reaches your ears",
    "A new character enters the scene, motives unclear",
    "A new character holds the key to a pending mystery",
    "You find a new lead on an existing quest",
}
