return {
    "The condition of buildings or objects",
    "The presence of a specific animal or creature",
    "An unexpected movement or action",
    "The angle from which the scene is observed",
    "A nearby conversation or interaction",
    "The background music  or sounds",
    "A lingering scent in the air",
    "The posture of a character",
    "A character's first impression about the scene",
    "The general demeanor of the people",
    "A detail of the local flora",
    "A unique architectural feature or design element",
    "The feel of a surface to the touch",
    "A character's facial expression or body language",
    "The way light filters into the scene",
    "An interesting piece of clothing or accessory",
    "The state of the sky and clouds",
    "The ambient noise level",
    "A notable ornament or detail in the environment",
    "The position of the sun or moon, or the time of day",
    "A wide shot of the landscape",
    "The rhythm or pace of actions and movements",
    "The patterns on clothing or objects",
    "The temperature of the air or surfaces",
    "A zoom-in or close-up on a significant detail",
    "The overall mood and atmosphere",
    "A whispered conversation or hushed tones",
    "The quality of materials in the surroundings",
    "A subtle, elusive sound permeating the background",
    "The desnity or sparseness of vegetation",
    "The interplay between natural and artificial elements",
    "The prevailing hues and tones of the scene",
    "The taste or sensation of something",
    "The contrast between light and shadow",
    "An ovorhead or bird's-eye view of the area",
    "The reverberation of sounds in the environment",
}
