return {
    "Courier's haste",
    "Secretive rendezvous",
    "Intense bartering",
    "Sentry duty",
    "Thorough search",
    "Hunt on the trail",
    "Scholarly dispute",
    "Village assembly",
    "Enthralling performance",
    "Alchemical experiment",
    "Vigilant patrol",
    "Soldiers on march",
    "Priests in prayer",
    "Harvest season",
    "Hasty abduction",
    "Elder's wisdom",
    "Dance rehearsal",
    "Healers at service",
    "Arrival of travelers",
    "Artists at work",
    "Frenzied construction",
    "Merchant negotiation",
    "Stealthy burglary",
    "Children's playtime",
    "Grim execution",
    "Somber mourning",
    "Knightly duel",
    "Tavern brawl",
    "Craftmanship display",
    "Tense interrogation",
    "Meticulous repair",
    "Insistent beggar",
    "Pilgrim's devotion",
    "Clandestine gambling",
    "Grand celebration",
    "Desperate chase",
}
