return {
    {
        'Spiced incense',
        'Smoky ash',
        'Animal musk',
        'Sweet honey',
        'Zesty fragrance',
        'Rotten eggs',
        'Bitter tang',
        'Minty breeze',
        'Vinegary odor',
        'Sharp chemics',
        'Dry bark',
        'Oily stench',
        'Musty books',
        'Pungent sweat',
        'Fresh soil',
        'Freshy herbal',
        'Fresh rain',
        'Citrus aroma',
        'Wet leaves',
        'Toasted aroma',
        'Saltwater breeze',
        'Earthy moss',
        'Rotten fruits',
        'Pine needles',
        'Creamy scent',
        'Dried herbs',
        'Blood tang',
        'Briny odor',
        'Spicy whiff',
        'Floral perfume',
        'Berries',
        'Burning wood',
        'Metallic rust',
        'Powdery perfume',
        'Peppery scent',
        'Sweet-sour',
    },

    {
        'Water drip',
        'Crackling fire',
        'Jangling keys',
        'Ticking clock',
        'Low hum',
        'Predator growl',
        'Splashing waves',
        'Eerie melody',
        'Footsteps',
        'Laughter',
        'Rustling leaves',
        'Distant thunder',
        'Muffled talk',
        'Fabric reap',
        'Hammering beat',
        'River rumble',
        'Coins clinking',
        'Sudden crack',
        'Buzzing insects',
        'Bird call',
        'Explosion',
        'Chiming bells',
        'Small creatures',
        'Sudden crack',
        'Warning cry',
        'Distant battle',
        'Creaking wood',
        'Rushing waterfall',
        'Pattering rain',
        'Animal echo',
        'Fluttering wings',
        'Metal clang',
        'Howling wind',
        'Whispers',
        'Eerie silence',
        'Babbling brook',
    },
}
